AWSTemplateFormatVersion: 2010-09-09
Description: Solution that uses SSM Automation to create encrypted snapshots of RDS clusters and then copy those snapshots to a different AWS region for DR purposes.
Parameters: 
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  SourceRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  TargetRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"
  GlobalClusterIdentifier:
    Default: global-db-cluster
    Type: String
    
Resources: 
  
  CrossRegionSnapshotCopySSMAutomation:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Name: 
        Fn::Join:
        - "-"
        - - "CRDR-SSMAutomation-Orders"
          - !Ref SourceRegion         
          - Fn::Select:
            - 0
            - Fn::Split:
              - "-"
              - Fn::Select:
                - 2
                - Fn::Split:
                  - "/"
                  - !Ref AWS::StackId
      Content:
        description: Aurora RDS Cluster Snapshot and Copy Automation Document
        parameters:
          SourceDBsnapshotArn:
            type: "String"
            description: "(Required) Arn of the cross region DR snapshot"
            default: ""           
        schemaVersion: '0.3'
        assumeRole: !Sub '{{resolve:secretsmanager:mr-app/CRDRSSMAutomationRoleArn}}'   
        mainSteps:          
          - name: CopyFailoverSnapshot
            action: 'aws:executeScript'
            inputs:
              Runtime: python3.7
              Handler: script_handler
              InputPayload:                
                SourceDBsnapshotArn: !Sub "{{SourceDBsnapshotArn}}"                
                automationid: '{{automation:EXECUTION_ID}}'
                sourceregion: !Ref SourceRegion
                targetregion: !Ref TargetRegion
                kmstargetkey: !Sub '{{resolve:secretsmanager:mr-app/orders-${TargetRegion}-${GlobalClusterIdentifier}-Snapshot-KeyArn${Env}}}' 
              Script: |-
                def script_handler(event, context):
                  import boto3, json, os,botocore
                  # Input parameters are provided by SSM document    
                  # DBSnapshotIdentifier = event.get("DBSnapshotIdentifier")
                  SourceDBsnapshotArn = event.get("SourceDBsnapshotArn")

                  DBSnapshotIdentifier = str(SourceDBsnapshotArn).split(":")[-1]
                  
                  sourceregion = event.get("sourceregion")
                  targetregion = event.get("targetregion")
                  kmstargetkey = event.get("kmstargetkey")
                  
                  print(DBSnapshotIdentifier)
                  print(SourceDBsnapshotArn)                  
                  print(kmstargetkey)

                  # Define Target region in the region_name.Following API
                  # is expected to run in Target region. Hence, by setting region_name
                  # to Target region, we achive that.
                  client = boto3.client('rds', region_name=targetregion)
                  try: 
                    response = client.copy_db_cluster_snapshot(
                        SourceDBClusterSnapshotIdentifier=SourceDBsnapshotArn,
                        TargetDBClusterSnapshotIdentifier=DBSnapshotIdentifier,
                        KmsKeyId=kmstargetkey, # KMS Key ID in Target region
                        CopyTags=False,
                        Tags=[
                                {
                                    'Key': 'NamingPrefix',
                                    'Value': 'orders'
                                },
                            ],
                        SourceRegion=sourceregion # This attribute will automatically generate presigned URL
                    )
                    print(response)
                    copystatus = response.get("DBClusterSnapshot").get("Status")
                    print("Status of Copying of Snapshot:" + str(copystatus))

                  except botocore.exceptions.ClientError as error:
                    raise error
                  except botocore.exceptions.ParamValidationError as error:
                    raise ValueError('The parameters you provided are incorrect: {}'.format(error))    
Outputs:
  AutomationDocument:
    Value: !Ref CrossRegionSnapshotCopySSMAutomation
   
    