AWSTemplateFormatVersion: 2010-09-09
Description: Cross Region DR Role to create/Copy/Restore DB Snapshots
Parameters: 
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  SourceRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  TargetRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"
  GlobalClusterIdentifier:
    Default: global-db-cluster
    Type: String
    
Resources: 

  CrossRegionSnapshotCopySSMAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Join:
        - "-"
        - - "CRDR-SSMRole"
          - !Ref SourceRegion
          - Fn::Select:
            - 0
            - Fn::Split:
              - "-"
              - Fn::Select:
                - 2
                - Fn::Split:
                  - "/"
                  - !Ref AWS::StackId
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - ssm.amazonaws.com
      Path: "/"
      Policies:
        - PolicyName: 
            Fn::Join:
            - "-"
            - - "CRDR-SSMPolicy"
              - !Ref SourceRegion
              - Fn::Select:
                - 0
                - Fn::Split:
                  - "-"
                  - Fn::Select:
                    - 2
                    - Fn::Split:
                      - "/"
                      - !Ref AWS::StackId
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ["rds:*"]
                Resource: 
                  - !Sub '{{resolve:secretsmanager:mr-app/orders-${SourceRegion}-${GlobalClusterIdentifier}${Env}}}'                  
                  - Fn::Join:
                    - ":"
                    - - "arn:aws:rds"
                      - !Ref SourceRegion
                      - !Ref AWS::AccountId
                      - "cluster-snapshot"
                      - Fn::Join:
                        - "-"
                        - -  !Sub '{{resolve:secretsmanager:mr-app/orders-${SourceRegion}-DBClusterIdentifier${Env}}}'               
                          - 'db-snapshot-*'
                   
              - Effect: Allow
                Action: ["rds:DescribeDBClusterSnapshots"]
                Resource: 
                  - "*"
              - Effect: Allow
                Action: ["rds:CopyDBClusterSnapshot", "rds:AddTagsToResource"]
                Resource: 
                  - Fn::Join:
                    - ":"
                    - - "arn:aws:rds"
                      - !Ref SourceRegion
                      - !Ref AWS::AccountId
                      - "cluster-snapshot"
                      - Fn::Join:
                        - "-"
                        - - !Sub '{{resolve:secretsmanager:mr-app/orders-${SourceRegion}-DBClusterIdentifier${Env}}}' 
                          - 'db-snapshot-*'
                  - Fn::Join:                    
                    - ":"
                    - - "arn:aws:rds"
                      - !Ref TargetRegion
                      - !Ref AWS::AccountId
                      - "cluster-snapshot"
                      - Fn::Join:
                        - "-"
                        - - !Sub '{{resolve:secretsmanager:mr-app/orders-${SourceRegion}-DBClusterIdentifier${Env}}}' 
                          - 'db-snapshot-*'
              - Effect: Allow
                Action: ["kms:DescribeKey","kms:CreateGrant"]
                Resource:  
                  - !Sub '{{resolve:secretsmanager:mr-app/orders-${GlobalClusterIdentifier}-StorageEncryptionKeyArn${Env}}}'                
                  - !Sub '{{resolve:secretsmanager:mr-app/orders-${TargetRegion}-${GlobalClusterIdentifier}-Snapshot-KeyArn${Env}}}' 
                  
  CrossRegionSnapshotCopySSMAutomationRoleArn:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "mr-app/CrossRegionSnapshotCopySSMAutomationRoleArn"
      Description: "Arn for CrossRegionSnapshotCopySSMAutomationRole"
      KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !GetAtt CrossRegionSnapshotCopySSMAutomationRole.Arn
      ReplicaRegions:
        - Region: us-west-2

Outputs:  
  SSMAutomationRole:
    Value: !Ref CrossRegionSnapshotCopySSMAutomationRole
  