AWSTemplateFormatVersion: 2010-09-09
Description: Solution that uses SSM Automation to restore encrypted snapshots of RDS cluster Orders DB
Parameters: 
  NamingPrefix:
    Type: String
    Description: Enter the Naming Prefix for resources created
    Default: "orders"
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  SourceRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  TargetRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"
  DBClusterIdentifier:
    Default: recociliation-db-cluster
    Type: String
  GlobalClusterIdentifier:
    Default: global-db-cluster
    Type: String
    
Resources: 
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds:
        - !Sub '{{resolve:ssm:Subnet1${Env}}}'
        - !Sub '{{resolve:ssm:Subnet2${Env}}}'
        - !Sub '{{resolve:ssm:Subnet3${Env}}}'
      DBSubnetGroupDescription: "orders-subnet-group"
  DBCluster:
    DependsOn:
      - SubnetGroup
    Type: AWS::RDS::DBCluster
    Properties:
      ServerlessV2ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 8
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBClusterIdentifier: !Sub '${NamingPrefix}-${DBClusterIdentifier}-${AWS::Region}${Env}'
      DBSubnetGroupName: !Ref SubnetGroup
      DeletionProtection: false
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      EnableIAMDatabaseAuthentication: true
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.04.0
      KmsKeyId: !Sub '{{resolve:secretsmanager:mr-app/orders-${TargetRegion}-${GlobalClusterIdentifier}-Snapshot-KeyArn${Env}}}' 
      MasterUsername: !Sub '{{resolve:secretsmanager:mr-app/${NamingPrefix}-${GlobalClusterIdentifier}-UserCredentials${Env}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:mr-app/${NamingPrefix}-${GlobalClusterIdentifier}-UserCredentials${Env}:SecretString:password}}'
      Port: '3306'
      StorageEncrypted: true
      VpcSecurityGroupIds: 
        - !Sub '{{resolve:ssm:${NamingPrefix}-aurora-mysql-sg-${TargetRegion}${Env}}}' 
      Tags:
        - Key: "NamingPrefix"
          Value: !Ref NamingPrefix
  DBInstance1:
    DependsOn:
      - DBCluster
      - SubnetGroup
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: 'true'
      DBClusterIdentifier: !Sub '${NamingPrefix}-${DBClusterIdentifier}-${AWS::Region}${Env}'
      DBInstanceIdentifier: !Sub '${NamingPrefix}-${DBClusterIdentifier}${Env}-1'
      Engine: aurora-mysql
      PubliclyAccessible: false
      MonitoringRoleArn: !Sub '{{resolve:secretsmanager:mr-app/${NamingPrefix}-${GlobalClusterIdentifier}-MonitoringIAMRoleArn${Env}}}'
      MonitoringInterval: 1
      DBInstanceClass: "db.r5.large"
      DBSubnetGroupName: !Ref SubnetGroup
      
  DBClusterArn:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'mr-app/${NamingPrefix}-${DBClusterIdentifier}-${AWS::Region}${Env}'
      Description: !Sub 'Reconciliation DBCluster Arn for ${NamingPrefix}'
      KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !GetAtt DBCluster.DBClusterArn
      ReplicaRegions:
        - Region: us-east-1

Outputs:
  DBEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
  DBPort:
    Value: !GetAtt DBCluster.Endpoint.Port