AWSTemplateFormatVersion: 2010-09-09
Description: Solution that uses SSM Automation to restore encrypted snapshots of RDS cluster Orders DB
Parameters: 
  NamingPrefix:
    Type: String
    Description: Enter the Naming Prefix for resources created
    Default: "orders"
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  SourceRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  TargetRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"
  DBClusterIdentifier:
    Default: recociliation-db-cluster
    Type: String
  GlobalClusterIdentifier:
    Default: global-db-cluster
    Type: String
Resources: 
  CrossRegionSnapshotRestoreSSMAutomation:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Name: 
        Fn::Join:
        - "-"
        - - "CRDR-SSMAutomation-Reconciliation"
          - !Ref SourceRegion         
          - Fn::Select:
            - 0
            - Fn::Split:
              - "-"
              - Fn::Select:
                - 2
                - Fn::Split:
                  - "/"
                  - !Ref AWS::StackId        
      Content:
        description: Aurora RDS Cluster Snapshot and Copy Automation Document
        parameters:
          SnapshotArn:
            type: "String"
            description: "(Required) Arn of the cross region DR snapshot"
            default: ""
        schemaVersion: '0.3'
        assumeRole: !Sub '{{resolve:secretsmanager:mr-app/CrossRegionSnapshotCopySSMAutomationRoleArn}}'   
        mainSteps:
            - name: RestoreSnapshot 
              action: 'aws:executeAwsApi'
              inputs:
                Service: rds
                Api: RestoreDBClusterFromSnapshot                    
                DBClusterIdentifier : !Sub '{{mr-app/${NamingPrefix}-recociliation-db-cluster-${TargetRegion}}}'
                Engine: aurora-mysql
                SnapshotIdentifier : !Sub "{{SnapshotArn}}"
                KmsKeyId:  !Sub '{{resolve:secretsmanager:mr-app/${NamingPrefix}-${TargetRegion}-${GlobalClusterIdentifier}-Snapshot-KeyArn${Env}}}' 
Outputs:
  AutomationDocument:
    Value: !Ref CrossRegionSnapshotRestoreSSMAutomation