AWSTemplateFormatVersion: "2010-09-09"
Description: 'ARC Region Switch Plan for Multi-Region Failover'

Parameters:
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  PrimaryRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  StandbyRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"
  DomainName:
    Type: String
    Description: The domain name for the Route53 hosted zone
    Default: "demo.io"
  PrimaryClusterArn:
    Type: String
    Description: ARN of the ECS cluster in the primary region
  StandbyClusterArn:
    Type: String
    Description: ARN of the ECS cluster in the standby region

Resources:
  RegionSwitchExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'RegionSwitchExecutionRole${Env}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: arc-region-switch.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RegionSwitchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "arc-region-switch:GetPlan"
                  - "arc-region-switch:GetPlanExecution"
                  - "arc-region-switch:ListPlanExecutions"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:SimulatePrincipalPolicy"
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/RegionSwitchExecutionRole${Env}'
              - Effect: Allow
                Action:
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:DescribeAlarmHistory"
                  - "cloudwatch:GetMetricStatistics"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ecs:DescribeServices"
                  - "ecs:UpdateService"
                Resource:
                  - !Sub
                    - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/*'
                    - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                  - !Sub
                    - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/*'
                    - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
              - Effect: Allow
                Action:
                  - "ecs:DescribeClusters"
                Resource:
                  - !Ref PrimaryClusterArn
                  - !Ref StandbyClusterArn
              - Effect: Allow
                Action:
                  - "ecs:ListServices"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "application-autoscaling:DescribeScalableTargets"
                  - "application-autoscaling:RegisterScalableTarget"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "rds:DescribeGlobalClusters"
                  - "rds:DescribeDBClusters"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "rds:FailoverGlobalCluster"
                  - "rds:SwitchoverGlobalCluster"
                Resource:
                  - !Sub 'arn:aws:rds::${AWS::AccountId}:global-cluster:catalog-global-db-cluster${Env}'
                  - !Sub '{{resolve:secretsmanager:mr-app/catalog-${PrimaryRegion}-global-db-cluster${Env}}}'
                  - !Sub '{{resolve:secretsmanager:mr-app/catalog-${StandbyRegion}-global-db-cluster${Env}}}'
              - Effect: Allow
                Action:
                  - "route53:ChangeResourceRecordSets"
                  - "route53:GetHostedZone"
                  - "route53:ListResourceRecordSets"
                Resource:
                  - !Sub
                    - 'arn:aws:route53:::hostedzone/${HostedZoneId}'
                    - HostedZoneId: !Sub '{{resolve:secretsmanager:HostedZoneIdSecret${Env}}}'
              - Effect: Allow
                Action:
                  - "route53:GetHealthCheck"
                  - "route53:UpdateHealthCheck"
                Resource: "arn:aws:route53:::healthcheck/*"

  RegionSwitchPlan:
    Type: AWS::ARCRegionSwitch::Plan
    Properties:
      Name: !Sub 'retail-store-ar-region-switch${Env}'
      ExecutionRole: !GetAtt RegionSwitchExecutionRole.Arn
      RecoveryApproach: activePassive
      PrimaryRegion: !Ref PrimaryRegion
      Regions:
        - !Ref PrimaryRegion
        - !Ref StandbyRegion
      Workflows:
        - WorkflowTargetAction: activate
          WorkflowDescription: "Scale up ECS services, failover database, then shift DNS traffic"
          Steps:
            - Name: scale-up-ecs-services
              ExecutionBlockType: Parallel
              ExecutionBlockConfiguration:
                ParallelConfig:
                  Steps:
                    - Name: scale-carts
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/carts${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/carts${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
                    - Name: scale-orders
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/orders${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/orders${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
                    - Name: scale-assets
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/assets${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/assets${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
                    - Name: scale-catalog
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/catalog${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/catalog${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
                    - Name: scale-checkout
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/checkout${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/checkout${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
                    - Name: scale-ui
                      ExecutionBlockType: ECSServiceScaling
                      ExecutionBlockConfiguration:
                        EcsCapacityIncreaseConfig:
                          Services:
                            - ClusterArn: !Ref PrimaryClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${PrimaryRegion}:${AWS::AccountId}:service/${ClusterName}/ui${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref PrimaryClusterArn]]
                            - ClusterArn: !Ref StandbyClusterArn
                              ServiceArn:
                                !Sub
                                  - 'arn:aws:ecs:${StandbyRegion}:${AWS::AccountId}:service/${ClusterName}/ui${Env}'
                                  - ClusterName: !Select [1, !Split ["/", !Ref StandbyClusterArn]]
                          TargetPercent: 200
                          CapacityMonitoringApproach: containerInsightsMaxInLast24Hours
                          TimeoutMinutes: 15
            - Name: failover-catalog-db
              ExecutionBlockType: AuroraGlobalDatabase
              ExecutionBlockConfiguration:
                GlobalAuroraConfig:
                  GlobalClusterIdentifier: !Sub 'catalog-global-db-cluster${Env}'
                  DatabaseClusterArns:
                    - !Sub '{{resolve:secretsmanager:mr-app/catalog-${PrimaryRegion}-global-db-cluster${Env}}}'
                    - !Sub '{{resolve:secretsmanager:mr-app/catalog-${StandbyRegion}-global-db-cluster${Env}}}'
                  Behavior: switchoverOnly
                  Ungraceful:
                    Ungraceful: failover
                  TimeoutMinutes: 20
            - Name: shift-dns-traffic
              ExecutionBlockType: Route53HealthCheck
              ExecutionBlockConfiguration:
                Route53HealthCheckConfig:
                  HostedZoneId: !Sub '{{resolve:secretsmanager:HostedZoneIdSecret${Env}}}'
                  RecordName: !Sub 'store.${DomainName}'
                  RecordSets:
                    - RecordSetIdentifier: PrimaryRegion
                      Region: !Ref PrimaryRegion
                    - RecordSetIdentifier: StandbyRegion
                      Region: !Ref StandbyRegion
                  TimeoutMinutes: 5

Outputs:
  RegionSwitchPlanArn:
    Description: ARN of the ARC Region Switch Plan
    Value: !Ref RegionSwitchPlan
  RegionSwitchExecutionRoleArn:
    Description: ARN of the Region Switch Execution Role
    Value: !GetAtt RegionSwitchExecutionRole.Arn
