AWSTemplateFormatVersion: "2010-09-09"
Description: "Canaries"

Parameters:
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  PrimaryRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  SecondaryRegion:
    Type: String
    Description: Enter the Secondary Region
    Default: "us-west-2"

Resources:
  SystemDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'System-Dashboard${Env}'
      DashboardBody: !Sub '{
    "widgets": [
        {
            "height": 6,
            "width": 6,
            "y": 0,
            "x": 0,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "ecommerce", "OrdersCreated${Env}", { "region": "${PrimaryRegion}" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${PrimaryRegion}",
                "title": "OrdersCreated-${PrimaryRegion}",
                "period": 60,
                "stat": "Sum"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 6,
            "x": 0,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "ecommerce", "OrdersCreated${Env}", { "region": "${SecondaryRegion}" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${PrimaryRegion}",
                "title": "OrdersCreated-${SecondaryRegion}",
                "period": 60,
                "stat": "Sum"
            }
        },
        {
            "height": 6,
            "width": 8,
            "y": 0,
            "x": 6,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/DynamoDB", "ReplicationLatency", "TableName", "cartsTable${Env}", "ReceivingRegion", "${SecondaryRegion}", { "region": "${PrimaryRegion}" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${PrimaryRegion}",
                "period": 1,
                "stat": "p99",
                "title": "Carts DDB Replication Latency to ${SecondaryRegion}"
            }
        },
        {
            "height": 6,
            "width": 8,
            "y": 6,
            "x": 6,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "AuroraGlobalDBReplicationLag", "DBClusterIdentifier", "orders-dbcluster-02-${SecondaryRegion}${Env}", "SourceRegion", "${PrimaryRegion}", { "region": "${SecondaryRegion}" } ],
                    [ ".", "AuroraGlobalDBRPOLag", ".", ".", ".", ".", { "region": "${SecondaryRegion}" } ],
                    [ ".", "AuroraGlobalDBReplicatedWriteIO", ".", ".", ".", ".", { "region": "${SecondaryRegion}" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${PrimaryRegion}",
                "stat": "p99",
                "period": 60,
                "title": "Orders Aurora DB - Cross-Region Latency Metrics"
            }
        },
        {
            "height": 6,
            "width": 10,
            "y": 0,
            "x": 14,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/Lambda", "Invocations" ],
                    [ ".", "Throttles" ],
                    [ ".", "Duration" ],
                    [ ".", "ConcurrentExecutions" ],
                    [ ".", "ClaimedAccountConcurrency" ],
                    [ ".", "Errors" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${PrimaryRegion}",
                "stat": "p99",
                "period": 60,
                "title": "Lambda Metrics - ${PrimaryRegion}"
            }
        },
        {
            "height": 6,
            "width": 10,
            "y": 6,
            "x": 14,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/Lambda", "Invocations" ],
                    [ ".", "Throttles" ],
                    [ ".", "Duration" ],
                    [ ".", "ConcurrentExecutions" ],
                    [ ".", "ClaimedAccountConcurrency" ],
                    [ ".", "Errors" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${SecondaryRegion}",
                "stat": "p99",
                "period": 60,
                "title": "Lambda Metrics - ${SecondaryRegion}"
            }
        }
    ]
}'