AWSTemplateFormatVersion: "2010-09-09"
Description: 'Base Infrastructure'

Parameters:
  Env:
    Type: String
    Default: ''
    Description: String to enable multiple deployments per AWS region
  NamingPrefix:
    Type: String
    Description: The prefix to be used for resources created by this template.
    Default: mr-app
  PrimaryRegion:
    Type: String
    Description: Enter the Primary Region
    Default: "us-east-1"
  StandbyRegion:
    Type: String
    Description: Enter the Standby Region
    Default: "us-west-2"

Mappings:
  RegionMap:
    us-east-1:
      "VPCCidrBlock": 10.1.0.0/16
      "PrivateCidrBlock1": 10.1.0.0/20
      "PrivateCidrBlock2": 10.1.16.0/20
      "PrivateCidrBlock3": 10.1.32.0/20
      "PublicCidrBlock1": 10.1.48.0/20
      "PublicCidrBlock2": 10.1.64.0/20
      "PublicCidrBlock3": 10.1.80.0/20
      "AvailabilityZoneId1": use1-az1
      "AvailabilityZoneId2": use1-az4
      "AvailabilityZoneId3": use1-az6
    us-west-2:
      "VPCCidrBlock": 10.2.0.0/16
      "PrivateCidrBlock1": 10.2.0.0/20
      "PrivateCidrBlock2": 10.2.16.0/20
      "PrivateCidrBlock3": 10.2.32.0/20
      "PublicCidrBlock1": 10.2.48.0/20
      "PublicCidrBlock2": 10.2.64.0/20
      "PublicCidrBlock3": 10.2.80.0/20
      "AvailabilityZoneId1": usw2-az1
      "AvailabilityZoneId2": usw2-az2
      "AvailabilityZoneId3": usw2-az3

Conditions:
  isPrimary: !Equals
    - !Ref AWS::Region
    - us-east-1
  isStandby: !Equals
    - !Ref AWS::Region
    - us-west-2

Resources:
  #VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !FindInMap [RegionMap, !Ref "AWS::Region", "VPCCidrBlock"]
      EnableDnsSupport: true
      EnableDnsHostnames: true
  VpcIdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub VpcId-${AWS::Region}${Env}
      Description: "VPC Id"
      KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !Ref Vpc
      ReplicaRegions:
        - Region: !If [isPrimary, us-west-2, us-east-1]
  # VpcCidrBlockParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type: String
  #     Name: !Sub VpcCidrBlock${Env}
  #     Value: !GetAtt Vpc.CidrBlock
  Peer:
    Condition: isStandby
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerRegion: !Ref PrimaryRegion
      PeerVpcId: !Sub '{{resolve:secretsmanager:VpcId-${PrimaryRegion}${Env}}}'
      VpcId: !Ref Vpc
  VpcPeerIdSecret:
    Condition: isStandby
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub VpcPeerId${Env}
      Description: "VPC Id"
      KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !Ref Peer
      ReplicaRegions:
        - Region: !Ref PrimaryRegion