management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${port:8080}

logging:
  level:
    root: debug

hibernate:
  dialect: org.hibernate.dialect.MariaDBDialect

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

  datasource:
    writer:
      jdbc-url: ${spring.datasource.writer.url}
      username:
      password:
      driverClassName: org.mariadb.jdbc.Driver
      connection-init-sql: SET aurora_replica_read_consistency = 'session'

    reader:
      jdbc-url: ${spring.datasource.reader.url}
      username:
      password:
      driverClassName: org.mariadb.jdbc.Driver
      connection-init-sql: SET aurora_replica_read_consistency = 'session'